#!/bin/bash

# Building with Pandoc
# We need https://github.com/jgm/pandoc/releases
# Download and install it
# Download http://www.tug.org/mactex/morepackages.html and install BasicTeX  for
# PDF generating

if [ ! -d "./output" ]; then mkdir ./output; fi
echo "" > "./output/source.markdown"
for chapfile in $(cat manuscript/Book.txt) 
do
  cat "manuscript/$chapfile" >> ./output/source.markdown
done

pandoc --smart --table-of-contents --output=./output/preview.pdf ./output/source.markdown
